spring.application.name=anishop


spring.jpa.hibernate.ddl-auto = none
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.dll-auto = create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans = true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#
#cuoc.dev=Tong-Quoc-Duoc
# #nakano.ja=Nakano-Miku
spring.profiles.active=uat